routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/linkstorage', function () {
    Artisan::call('storage:link');
});


Route::get('/','Front\WelcomeController@welcome');

Route::get('dynamics/{param}','Front\WelcomeController@dynamics');

Route::get('/mailform', function () {
    return view('mail.mailform');
});

Route::post('sendMail','Front\TestmailController@sendmail');

Route::get('/whoWeare',function (){
    return view('front.whoWeare');
});

Route::resource('resetpassword','Security\ForgotPasswordController');

Route::get('reinitiate_message', 'Security\ForgotPasswordController@reinitiate_message');

Route::get('forgot_password', 'Security\ForgotPasswordController@index');

Route::post('/updateProfile','ProfileController@updateProfile')->middleware('auth');


Route::get('/showLogin','Auth\LoginController@showLoginForm');

////////////Header

//Dashboard Admin

Route::get('entrepreneur_created','AdminController@entrepreneur_created')->middleware('auth');

Route::resource('user','UserController')->middleware('auth');

Route::get('entrepreneurs','AdminController@entrepreneurs')->middleware('auth');

Route::resource('article','ArticleController')->middleware('auth');
Route::get('articles_updated/{param}','EntrepreneurController@articles_updated')->middleware('auth');
Route::get('articles_closed/{param}','EntrepreneurController@articles_closed')->middleware('auth');


//Dashboard Entrepreneur

Route::get('dashboard_events','EntrepreneurController@dashboard_events')->middleware('auth');
Route::get('dashboard_infographies','EntrepreneurController@dashboard_infographies')->middleware('auth');
Route::get('dashboard_digitechs','EntrepreneurController@dashboard_digitechs')->middleware('auth');
Route::get('dashboard_assistances','EntrepreneurController@dashboard_assistances')->middleware('auth');
Route::get('dashboard_communications','EntrepreneurController@dashboard_communications')->middleware('auth');

Route::get('dashboard_magazines','EntrepreneurController@dashboard_magazines')->middleware('auth');
Route::get('dashboard_economies','EntrepreneurController@dashboard_economies')->middleware('auth');
Route::get('dashboard_finances','EntrepreneurController@dashboard_finances')->middleware('auth');
Route::get('dashboard_managements','EntrepreneurController@dashboard_managements')->middleware('auth');

Route::get('closed_events','EntrepreneurController@closed_events')->middleware('auth');

Route::get('closed_infographies','EntrepreneurController@closed_infographies')->middleware('auth');

Route::get('closed_digiteches','EntrepreneurController@closed_digiteches')->middleware('auth');

Route::get('closed_assistances','EntrepreneurController@closed_assistances')->middleware('auth');

Route::get('closed_communications','EntrepreneurController@closed_communications')->middleware('auth');

Route::get('dashboard_jobs','EntrepreneurController@dashboard_jobs')->middleware('auth');



   ////Blog
Route::resource('blog','BlogController');

Route::get('blogs_created','BloggerController@blogs_created')->middleware('auth');
Route::get('blogs_published','BloggerController@blogs_published')->middleware('auth');
Route::get('blogs_updated','BloggerController@blogs_updated')->middleware('auth');
Route::get('blogs_closed','BloggerController@blogs_closed')->middleware('auth');
//Route::get('blogs_comments','BloggerController@blogs_comments')->middleware('auth');


Route::resource('job','JobController');
Route::get('jobs_created/{param}','RecruiterController@jobs_created')->middleware('auth');
Route::get('jobs_published/{param}','RecruiterController@jobs_published')->middleware('auth');
Route::get('jobs_updated/{param}','RecruiterController@jobs_updated')->middleware('auth');
Route::get('jobs_closed/{param}','RecruiterController@jobs_closed')->middleware('auth');

Route::resource('applyjob','ApplicantController');
Route::get('applicants/{id}','ApplicantController@applicants')->middleware('auth');

Route::get('downloadCv/{id}','ApplicantController@downloadCv')->middleware('auth');

Route::get('downloadCoverletter/{id}','ApplicantController@downloadCoverletter')->middleware('auth');

Route::get('download/{param}/{id}','DownloadController@downloadArticle');

Route::get('blogs','Front\IndexController@blogs');

Route::get('last_blogs','Front\IndexController@last_blogs');

Route::resource('comment','CommentController');

Route::get('comments/{id}','CommentController@commentsById');


    ////Job
Route::get('jobs',function (){
    return view('front.job.index');
});

Route::get('job_offers','JobController@job_offers');

Route::get('job_asks','JobController@job_asks');

   /// library
Route::get('/library/management',function (){
    return view('front.library.management.index');
});

Route::get('/library/economy',function (){
    return view('front.library.economy.index');
});

Route::get('/library/finance',function (){
    return view('front.library.finance.index');
});

          /// Magazine
Route::get('/magazine',function (){
    return view('front.magazine.index');
});
         ///Service

Route::get('service/adviceAssistance',function (){
    return view('front.service.adviceAssistance.index');
});
Route::get('service/communication',function (){
    return view('front.service.communication.index');
});

Route::get('service/digitech',function (){
    return view('front.service.digitech.index');
});
Route::resource('reservations','ReservationController');
Route::resource('event','EventController');
Route::resource('infography','InfographyController');
Route::resource('communication','CommunicationController');
Route::resource('assistance','AssistanceController');
Route::resource('digitech','DigitechController');

Route::get('reservation_event/{param}','ServiceController@reservation_event');
Route::get('reservation_infography/{param}','ServiceController@reservation_infography');
Route::get('reservation_communication/{param}','ServiceController@reservation_communication');
Route::get('reservation_assistance/{param}','ServiceController@reservation_assistance');
Route::get('reservation_digitech/{param}','ServiceController@reservation_digitech');


//ARTICLES

Route::get('library_articles/{param}','LibraryController@library_articles');

Route::get('/service/event',function (){
    return view('front.service.event.index');
});
Route::get('/service/infographicGraphic',function (){
    return view('front.service.infographicGraphic.index');
});

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('contactus','Front\ContactUsController');

Route::resource('newsletter','Front\NewsletterController');

Route::get('message/{message}','EntrepreneurController@message')->middleware('auth');

Route::get('dynamicsfront_display','EntrepreneurController@dynamicsfront_display')->middleware('auth');

Route::get('dynamicsfront/{param}','EntrepreneurController@dynamicsfront')->middleware('auth');

Route::resource('imagehead','ImageHeadController')->middleware('auth');

Route::resource('agency','AgencyController')->middleware('auth');

Route::resource('contact','ContactController')->middleware('auth');

Route::resource('socialnetwork','SocialNetworkController')->middleware('auth');


Route::resource('subscriber','Front\SubscriberController');

Route::group(['middleware' => 'auth','prefix'=> 'mailing'], function() {

    Route::get('','EntrepreneurController@mailing');

    Route::get('{param}','EntrepreneurController@mail_to');

});
Route::resource('mailto','MailtoController')->middleware('auth');;

Auth::routes();

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\API\Constant;
use App\Http\Controllers\Front\SendmailController;
use App\Models\Economy;
use App\Models\Finance;
use App\Models\Magazine;
use App\Models\Management;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Validator;

class ArticleController extends Controller
{
    public $constant;

    public function __construct()
    {
        $this->constant = new Constant();
    }

    public function index()
    {
        //
    }


    public function create()
    {
        //
    }


    public function store(Request $request)
    {

        if($request->hasFile('photo')){
            $file = $request->file('photo');
            $allowedFileTypes = config('app.allowedFileTypes');
            $maxFileSize = config('app.maxFileSize');
            $rules = [
                'photo' => 'required|mimes:'.$allowedFileTypes.'|max:'.$maxFileSize
            ];

            $this->validate($request, $rules);

        }
        if($request['type_article'] == 'magazine'){
            $check_article = Magazine::where([
                'title'      => $request['title'],
                'state_id'   => $request['state_id']
            ])->get()->first();

            if($check_article){
                return  redirect()->back()->with('success',$this->constant::ARTICLE_ALREADY_REGISTERED);
            }

            if($request['photo']){

                $avatar   = $request->file('photo')->store('avatars');

                $attributes = $request->all();



                Arr::set($attributes, 'photo', $avatar);

                  Magazine::create($attributes);

                $param_publication = "magazine";

                (new SendmailController())->notification_new_publication($param_publication);

                return redirect()->back()->with('success',$this->constant::SUCCESS_REGISTER);
            }
            $attributes = $request->all();

            Magazine::create($attributes);

            $param_publication = "magazine";

            (new SendmailController())->notification_new_publication($param_publication);

            return redirect()->back()->with('success',$this->constant::SUCCESS_REGISTER);

        }

        if($request['type_article'] == 'economy'){
            $check_article = Economy::where([
                'title'      => $request['title'],
                'state_id'   => $request['state_id']
            ])->get()->first();

            if($check_article){
                return  redirect()->back()->with('success',$this->constant::ARTICLE_ALREADY_REGISTERED);
            }

            if($request['photo']){

                $avatar   = $request->file('photo')->store('avatars');

                $attributes = $request->all();

                Arr::set($attributes, 'photo', $avatar);

                Economy::create($attributes);

                $param_publication = "economy";

                (new SendmailController())->notification_new_publication($param_publication);

                return redirect()->back()->with('success',$this->constant::SUCCESS_REGISTER);
            }
            $attributes = $request->all();

               Economy::create($attributes);

            $param_publication = "economy";

            (new SendmailController())->notification_new_publication($param_publication);

            return redirect()->back()->with('success',$this->constant::SUCCESS_REGISTER);

        }

        if($request['type_article'] == 'finance'){
            $check_article = Finance::where([
                'title'      => $request['title'],
                'state_id'   => $request['state_id']
            ])->get()->first();

            if($check_article){
                return  redirect()->back()->with('success',$this->constant::ARTICLE_ALREADY_REGISTERED);
            }

            if($request['photo']){
                $attributes = $request->all();

                $avatar   = $request->file('photo')->store('avatars');


                Arr::set($attributes, 'photo', $avatar);

                Finance::create($attributes);

                $param_publication = "finance";

                (new SendmailController())->notification_new_publication($param_publication);

                return redirect()->back()->with('success',$this->constant::SUCCESS_REGISTER);
            }
            $attributes = $request->all();

             Finance::create($attributes);

            $param_publication = "finance";
            (new SendmailController())->notification_new_publication($param_publication);

            return redirect()->back()->with('success',$this->constant::SUCCESS_REGISTER);

        }

        if($request['type_article'] == 'management'){
            $check_article = Management::where([
                'title'      => $request['title'],
                'state_id'   => $request['state_id']
            ])->get()->first();

            if($check_article){
                return  redirect()->back()->with('success',$this->constant::ARTICLE_ALREADY_REGISTERED);
            }

            if($request['photo']){
                $attributes = $request->all();

                $avatar   = $request->file('photo')->store('avatars');


                Arr::set($attributes, 'photo', $avatar);

                Management::create($attributes);

                $param_publication = "management";
                (new SendmailController())->notification_new_publication($param_publication);

                return redirect()->back()->with('success',$this->constant::SUCCESS_REGISTER);
            }
            $attributes = $request->all();

            Management::create($attributes);

            $param_publication = "management";

            (new SendmailController())->notification_new_publication($param_publication);

            return redirect()->back()->with('success',$this->constant::SUCCESS_REGISTER);
        }




    }


    public function show(Request $request)
    {
        if($request['type_article'] == 'magazine'){

            $article = Magazine::findOrFail($request['article_id']);

            $article->update($request->all());

            return redirect()->back()->with('success',$this->constant::ARTICLE_SUCCESS_CLOSED);

        }

        if($request['type_article'] == 'economy'){


            $article = Economy::findOrFail($request['article_id']);

            $article->update($request->all());

            return redirect()->back()->with('success',$this->constant::ARTICLE_SUCCESS_CLOSED);

        }

        if($request['type_article'] == 'finance'){
            $article = Finance::findOrFail($request['article_id']);

            $article->update($request->all());

            return redirect()->back()->with('success',$this->constant::ARTICLE_SUCCESS_CLOSED);

        }

        if($request['type_article'] == 'management'){
            $article = Management::findOrFail($request['article_id']);

            $article->update($request->all());

            return redirect()->back()->with('success',$this->constant::ARTICLE_SUCCESS_CLOSED);
        }
    }


    public function edit($id)
    {

    }


    public function update(Request $request)
    {

        if($request['type_article'] == 'magazine'){

            $article = Magazine::findOrFail($request['article_id']);
            if($request['photo']){

                $avatar   = $request->file('photo')->store('avatars');

                $attributes = $request->all();

                Arr::set($attributes, 'photo', $avatar);

                $article->update($attributes);

                return redirect()->back()->with('success',$this->constant::SUCCESS_UPDATE);
            }
            $attributes = $request->all();

            $article->update($attributes);

            return redirect()->back()->with('success',$this->constant::SUCCESS_UPDATE);

        }

        if($request['type_article'] == 'economy'){


            $article = Economy::findOrFail($request['article_id']);


            if($request['photo']){

                $avatar   = $request->file('photo')->store('avatars');

                $attributes = $request->all();

                Arr::set($attributes, 'photo', $avatar);

                $article->update($attributes);

                return redirect()->back()->with('success',$this->constant::SUCCESS_UPDATE);
            }
            $attributes = $request->all();

            $article->update($attributes);

            return redirect()->back()->with('success',$this->constant::SUCCESS_UPDATE);

        }

        if($request['type_article'] == 'finance'){
            $article = Finance::findOrFail($request['article_id']);


            if($request['photo']){
                $attributes = $request->all();

                $avatar   = $request->file('photo')->store('avatars');


                Arr::set($attributes, 'photo', $avatar);

                $article->update($attributes);

                return redirect()->back()->with('success',$this->constant::SUCCESS_UPDATE);
            }
            $attributes = $request->all();

            $article->update($attributes);

            return redirect()->back()->with('success',$this->constant::SUCCESS_UPDATE);

        }

        if($request['type_article'] == 'management'){
            $article = Management::findOrFail($request['article_id']);

            if($request['photo']){
                $attributes = $request->all();

                $avatar   = $request->file('photo')->store('avatars');


                Arr::set($attributes, 'photo', $avatar);

                $article->update($attributes);

                return redirect()->back()->with('success',$this->constant::SUCCESS_REGISTER);
            }
            $attributes = $request->all();

            $article->update($attributes);

            return redirect()->back()->with('success',$this->constant::SUCCESS_REGISTER);
        }
    }

    public function destroy(Request $request)
    {

resources/views/dashboard/entrepreneur/article/management/head.blade.php
<h4 style="color: #1cc88a">Gestion</h4>

<div class="row" style="margin-bottom: 14px;">
    <button class="btn btn-info" style="margin-left: 13px;"
            data-toggle="modal"
            data-target="#addarticle"
    >Ajouter un manuel</button>
    /
    <button class="btn btn-info" style="margin-left: 10px;"
    >
        <a href="{{url('articles_updated','management')}}">
            <strong style="color: yellow">Manuels mis à jour</strong>  </a></button>
    /
    <button class="btn btn-info" style="margin-left: 10px;">
        <a href="{{url('articles_closed','management')}}"><strong style="color: green">Manuels clôturés</strong></a></button>
</div>

resources/views/dashboard/entrepreneur/article/management/published.blade.php
@extends('layouts.master')
@section('content')

    <div class="box-body">
        <!-- Begin Page Content -->
        <div class="container-fluid">

            @include('dashboard.entrepreneur.article.management.head')

            @if($articles->isEmpty())
                <h1 style="text-align: center;color: #2E5539;">Aucun résultat ne correspond à votre recherche</h1>
            @else
            <!-- DataTales Example -->
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Liste de vos manuels de Gestion publiés</h6>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead class="thead-dark">
                                <tr>
                                    <th>Titre</th>
                                    <th>Domaine</th>
                                    <th>Date de publication </th>
                                    <th>Etat</th>
                                </tr>
                                </thead>

                                <tbody>
                                    @foreach($articles as $article)
                                        <tr>
                                            <td class="border px-4 py-2">{{$article->title}}</td>
                                            <td class="border px-4 py-2">{{$article->sector->name}}</td>

                                            <td class="border px-4 py-2">{{$article->publication_date}}</td>

                                            <td class="border px-4 py-2">
                                                <button style="color: green;"
                                                        data-blogid          = "{{$article->id}}"
                                                        data-toggle="modal"
                                                        data-target="#closeblog"
                                                >{{$article->state->description}}</button>
                                            </td>
                                            @if($article->photo)
                                                <td>
                                                    <button style="color: green;"
                                                    >
                                                        <a href="{{url('download/management',$article->id)}}">
                                                            <i class="fas fa-eye fa-sm">Voir</i>
                                                        </a>
                                                    </button>
                                                </td>
                                            @endif
                                            <td>
                                                <button class="btn btn-info"
                                                        data-blogid            = "{{$article->id}}"
                                                        data-title             = "{{$article->title}}"
                                                        data-description       = "{{$article->description}}"
                                                        data-toggle="modal"
                                                        data-target="#editblog"
                                                >Détails</button>
                                                /
                                                <button class="btn btn-danger"
                                                        data-blogid = "{{$article->id}}"
                                                        data-toggle="modal"
                                                        data-target="#deleteblog"
                                                >Supprimer</button>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!--Modal Edit User-->
                <div class="modal fade" id="editblog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <h4 class="modal-title" id="myModalLabel">Editer un manuel</h4>
                            </div>
                            <form action="{{route('article.update','test')}}" method="post" enctype="multipart/form-data">
                                {{method_field('patch')}}
                                {{csrf_field()}}
                                <div class="modal-body">
                                    <input type="hidden" name="article_id" id="blog_id">
                                    <input type="hidden"   name="state_id"  value="{{$state_updated_id}}">
                                    <input type="hidden"   name="publication_date"  value="{{$publication_date}}">
                                    <input type="hidden" name="type_article" value="management">
                                    <div class="form-group">
                                        <label for="">Titre de l'article</label>
                                        <input type="text"  class="form-control" name="title"  id="title">
                                    </div>

                                    <div class="form-group">
                                        <label for="">Description de l'article</label>
                                        <textarea type="text" rows="12" class="form-control" name="description"  id="description"></textarea>
                                    </div>

                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
                                    <button type="submit" class="btn btn-success">Enregistrer les changements</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            @endif
        </div>
        <!--Modal Edit User-->
        <div class="modal fade" id="addarticle" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Ajouter un manuel</h4>
                    </div>
                    <form action="{{route('article.store','test')}}" method="post" enctype="multipart/form-data">
                        {{method_field('post')}}
                        {{csrf_field()}}
                        <div class="modal-body">

                            <input type="hidden"   name="state_id"  value="{{$state_published_id}}">
                            <input type="hidden"   name="publication_date"  value="{{$publication_date}}">
                            <input type="hidden" name="type_article" value="management">
                            <div class="flex flex-col mb-4">
                                <label class="">Domaine</label>
                                <select class="form-control" name="sector_id" required>
                                    @foreach($sectors as $sector)
                                        <option value="{{$sector->id}}">{{$sector->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="flex flex-col mb-4">
                                <label class="mb-2 font-bold text-lg text-grey-darkest">Image</label>
                                <input class="border py-2 px-3 text-grey-darkest" type="file" name="photo">
                            </div>
                            <div class="form-group">
                                <label for="">Titre de l'article</label>
                                <input type="text"  class="form-control" name="title" required>
                            </div>

                            <div class="form-group">
                                <label for="">Description de l'article</label>
                                <textarea type="text" rows="12" class="form-control" name="description" required></textarea>
                            </div>

                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
                            <button type="submit" class="btn btn-success">Publier</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

    <!-- Modal -->

    <div class="modal modal-danger fade" id="closeblog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title text-center" id="myModalLabel">Confirmation de la clôture</h4>
                </div>
                <form action="{{route('article.show','test')}}" method="get">
                    {{csrf_field()}}
                    <div class="modal-body">
                        <p class="text-center">
                            Voulez-vous clôturer ce manuel ?
                        </p>
                        <input type="hidden" name="article_id" id="blog_id">
                        <input type="hidden"   name="state_id"  value="{{$state_closed_id}}">
                        <input type="hidden"   name="publication_date"  value="{{$publication_date}}">
                        <input type="hidden" name="type_article" value="management">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-success" data-dismiss="modal">Non,Annuler</button>
                        <button type="submit" class="btn btn-warning">Oui,Clôturer</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="modal modal-danger fade" id="deleteblog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title text-center" id="myModalLabel">Confirmation de la suppression</h4>
                </div>
                <form action="{{route('article.destroy','test')}}" method="post">
                    {{method_field('delete')}}
                    {{csrf_field()}}
                    <div class="modal-body">
                        <p class="text-center">
                            Ëtes-vous sûrs de supprimer ce manuel ?
                        </p>
                        <input type="hidden" name="article_id" id="blog_id">
                        <input type="hidden" name="type_article" value="management">

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-success" data-dismiss="modal">Non,Annuler</button>
                        <button type="submit" class="btn btn-warning">Oui,Supprimer</button>
                    </div>
                </form>
            </div>
        </div>
    </div>



@endsection