routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/linkstorage', function () {
    Artisan::call('storage:link');
});


Route::get('/','Front\WelcomeController@welcome');

Route::get('dynamics/{param}','Front\WelcomeController@dynamics');

Route::get('/mailform', function () {
    return view('mail.mailform');
});

Route::post('sendMail','Front\TestmailController@sendmail');

Route::get('/whoWeare',function (){
    return view('front.whoWeare');
});

Route::resource('resetpassword','Security\ForgotPasswordController');

Route::get('reinitiate_message', 'Security\ForgotPasswordController@reinitiate_message');

Route::get('forgot_password', 'Security\ForgotPasswordController@index');

Route::post('/updateProfile','ProfileController@updateProfile')->middleware('auth');


Route::get('/showLogin','Auth\LoginController@showLoginForm');

////////////Header

//Dashboard Admin

Route::get('entrepreneur_created','AdminController@entrepreneur_created')->middleware('auth');

Route::resource('user','UserController')->middleware('auth');

Route::get('entrepreneurs','AdminController@entrepreneurs')->middleware('auth');

Route::resource('article','ArticleController')->middleware('auth');
Route::get('articles_updated/{param}','EntrepreneurController@articles_updated')->middleware('auth');
Route::get('articles_closed/{param}','EntrepreneurController@articles_closed')->middleware('auth');


//Dashboard Entrepreneur

Route::get('dashboard_events','EntrepreneurController@dashboard_events')->middleware('auth');
Route::get('dashboard_infographies','EntrepreneurController@dashboard_infographies')->middleware('auth');
Route::get('dashboard_digitechs','EntrepreneurController@dashboard_digitechs')->middleware('auth');
Route::get('dashboard_assistances','EntrepreneurController@dashboard_assistances')->middleware('auth');
Route::get('dashboard_communications','EntrepreneurController@dashboard_communications')->middleware('auth');

Route::get('dashboard_magazines','EntrepreneurController@dashboard_magazines')->middleware('auth');
Route::get('dashboard_economies','EntrepreneurController@dashboard_economies')->middleware('auth');
Route::get('dashboard_finances','EntrepreneurController@dashboard_finances')->middleware('auth');
Route::get('dashboard_managements','EntrepreneurController@dashboard_managements')->middleware('auth');

Route::get('closed_events','EntrepreneurController@closed_events')->middleware('auth');

Route::get('closed_infographies','EntrepreneurController@closed_infographies')->middleware('auth');

Route::get('closed_digiteches','EntrepreneurController@closed_digiteches')->middleware('auth');

Route::get('closed_assistances','EntrepreneurController@closed_assistances')->middleware('auth');

Route::get('closed_communications','EntrepreneurController@closed_communications')->middleware('auth');

Route::get('dashboard_jobs','EntrepreneurController@dashboard_jobs')->middleware('auth');



   ////Blog
Route::resource('blog','BlogController');

Route::get('blogs_created','BloggerController@blogs_created')->middleware('auth');
Route::get('blogs_published','BloggerController@blogs_published')->middleware('auth');
Route::get('blogs_updated','BloggerController@blogs_updated')->middleware('auth');
Route::get('blogs_closed','BloggerController@blogs_closed')->middleware('auth');
//Route::get('blogs_comments','BloggerController@blogs_comments')->middleware('auth');


Route::resource('job','JobController');
Route::get('jobs_created/{param}','RecruiterController@jobs_created')->middleware('auth');
Route::get('jobs_published/{param}','RecruiterController@jobs_published')->middleware('auth');
Route::get('jobs_updated/{param}','RecruiterController@jobs_updated')->middleware('auth');
Route::get('jobs_closed/{param}','RecruiterController@jobs_closed')->middleware('auth');

Route::resource('applyjob','ApplicantController');
Route::get('applicants/{id}','ApplicantController@applicants')->middleware('auth');

Route::get('downloadCv/{id}','ApplicantController@downloadCv')->middleware('auth');

Route::get('downloadCoverletter/{id}','ApplicantController@downloadCoverletter')->middleware('auth');

Route::get('download/{param}/{id}','DownloadController@downloadArticle');

Route::get('blogs','Front\IndexController@blogs');

Route::get('last_blogs','Front\IndexController@last_blogs');

Route::resource('comment','CommentController');

Route::get('comments/{id}','CommentController@commentsById');


    ////Job
Route::get('jobs',function (){
    return view('front.job.index');
});

Route::get('job_offers','JobController@job_offers');

Route::get('job_asks','JobController@job_asks');

   /// library
Route::get('/library/management',function (){
    return view('front.library.management.index');
});

Route::get('/library/economy',function (){
    return view('front.library.economy.index');
});

Route::get('/library/finance',function (){
    return view('front.library.finance.index');
});

          /// Magazine
Route::get('/magazine',function (){
    return view('front.magazine.index');
});
         ///Service

Route::get('service/adviceAssistance',function (){
    return view('front.service.adviceAssistance.index');
});
Route::get('service/communication',function (){
    return view('front.service.communication.index');
});

Route::get('service/digitech',function (){
    return view('front.service.digitech.index');
});
Route::resource('reservations','ReservationController');
Route::resource('event','EventController');
Route::resource('infography','InfographyController');
Route::resource('communication','CommunicationController');
Route::resource('assistance','AssistanceController');
Route::resource('digitech','DigitechController');

Route::get('reservation_event/{param}','ServiceController@reservation_event');
Route::get('reservation_infography/{param}','ServiceController@reservation_infography');
Route::get('reservation_communication/{param}','ServiceController@reservation_communication');
Route::get('reservation_assistance/{param}','ServiceController@reservation_assistance');
Route::get('reservation_digitech/{param}','ServiceController@reservation_digitech');


//ARTICLES

Route::get('library_articles/{param}','LibraryController@library_articles');

Route::get('/service/event',function (){
    return view('front.service.event.index');
});
Route::get('/service/infographicGraphic',function (){
    return view('front.service.infographicGraphic.index');
});

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('contactus','Front\ContactUsController');

Route::resource('newsletter','Front\NewsletterController');

Route::get('message/{message}','EntrepreneurController@message')->middleware('auth');

Route::get('dynamicsfront_display','EntrepreneurController@dynamicsfront_display')->middleware('auth');

Route::get('dynamicsfront/{param}','EntrepreneurController@dynamicsfront')->middleware('auth');

Route::resource('imagehead','ImageHeadController')->middleware('auth');

Route::resource('agency','AgencyController')->middleware('auth');

Route::resource('contact','ContactController')->middleware('auth');

Route::resource('socialnetwork','SocialNetworkController')->middleware('auth');


Route::resource('subscriber','Front\SubscriberController');

Route::group(['middleware' => 'auth','prefix'=> 'mailing'], function() {

    Route::get('','EntrepreneurController@mailing');

    Route::get('{param}','EntrepreneurController@mail_to');

});
Route::resource('mailto','MailtoController')->middleware('auth');;

Auth::routes();

app/Models/Blog.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{

    protected $fillable=['user_id','title','description','photo', 'publication_date','state_id','sector_id'];

    public function user(){
        return $this->belongsTo(User::class);
    }
    public function comments(){
        return $this->hasMany(Comment::class);
    }

    public function state(){
        return $this->belongsTo(State::class);
    }

    public function sector(){
        return $this->belongsTo(Sector::class);
    }

}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\API\Constant;
use App\Http\Controllers\Front\SendmailController;
use App\Models\Blog;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;

class BlogController extends Controller
{
    public $constant;

    public function __construct()
    {
        $this->constant = new  Constant();
    }




    public function store(Request $request)
    {
        $check_blog = Blog::where([
            'user_id'    => $request['blogger_id'],
            'title'      => $request['title'],
            'state_id'   => $request['state_id']
        ])->get()->first();

        if($check_blog){
            return  redirect()->back()->with('success',$this->constant::BLOG_ALREADY_REGISTERED);
        }

        if($request['photo']){
            $attributes = $request->all();

            $avatar   = $request->file('photo')->store('avatars');

            $attributes = $request->all();

            Arr::set($attributes, 'photo', $avatar);

            Blog::create($attributes);

                $param_publication = "article";

               (new SendmailController())->notification_new_publication($param_publication);

            return redirect()->back()->with('success',$this->constant::SUCCESS_REGISTER);
        }
        $attributes = $request->all();

        Blog::create($attributes);

        $param_publication = "article";

        (new SendmailController())->notification_new_publication($param_publication);

        return redirect()->back()->with('success',$this->constant::SUCCESS_REGISTER);


    }


    public function update(Request $request)
    {

        $blog = Blog::findOrFail($request['blog_id']);

       /* if($request->photo){

            $avatar     = $request->file('photo')->store('avatars');

            Arr::set($attributes, 'photo', $avatar);

            $blog->update($attributes);

            return redirect()->back()->with('success',$this->constant::SUCCESS_UPDATE);
        }*/

        $blog->update($request->all());

        return redirect()->back()->with('success',$this->constant::SUCCESS_UPDATE);

    }


    public function destroy(Request $request)
    {
        $blog = Blog::findOrFail($request['blog_id']);
        $blog->delete();
        return redirect()->back()->with('success',$this->constant::SUCCESS_DELETE);
    }
    public function show(Request $request){

        $blog = Blog::findOrFail($request['blog_id']);

        $attributes = $request->all();

        $blog->update($attributes);

        return redirect()->back()->with('success',$this->constant::SUCCESS_BLOG_CLOSED);
    }

}

app/Http/Controllers/BloggerController.php
<?php

namespace App\Http\Controllers;

use App\API\Constant;
use App\API\DateInfos;
use App\Models\Blog;
use App\Models\ContactUs;
use App\Models\Country;
use App\Models\Profession;
use App\Models\Sector;

class BloggerController extends Controller
{

    public $constant;
    public $date_today;


    public function __construct()
    {
        $this->constant = new Constant();
        $this->date_today = new DateInfos();

    }

    public function blogs_created(){

        $last_messages = ContactUs::where(['response' => null])->get();

        $number_last_messages = $last_messages->count();

        //States

        $state_submitted_id      = (new Constant())::SUBMITTED_ID;
        $state_closed_id      = (new Constant())::CLOSED_ID;
        $state_published_id   = (new Constant())::PUBLISHED_ID;

        $publication_date = $this->date_today->date_today();
        $countries       = Country::all();
        $professions     = Profession::all();
        $sectors         = Sector::all();

        //Profiles
        $profile_admin_id         = (new Constant())::ADMIN_ID;
        $profile_entrepreneur_id  = (new Constant())::ENTREPRENEUR_ID;
        $profile_recruiter_id     = (new Constant())::RECRUITER_ID;

        return view('dashboard.entrepreneur.blogs.created',compact(
            'profile_admin_id', 'profile_entrepreneur_id', 'profile_recruiter_id',
            'state_submitted_id','state_closed_id','countries','professions','number_last_messages','last_messages'
            , 'countries','professions','sectors', 'publication_date','state_published_id'
        ));
    }
    public function blogs_published(){

        $last_messages = ContactUs::where(['response' => null])->get();

        $number_last_messages = $last_messages->count();

        $publication_date = $this->date_today->date_today();
        $countries       = Country::all();
        $professions     = Profession::all();
        $sectors         = Sector::all();

        //Profiles
        $profile_admin_id         = (new Constant())::ADMIN_ID;
        $profile_entrepreneur_id  = (new Constant())::ENTREPRENEUR_ID;

        $profile_recruiter_id     = (new Constant())::RECRUITER_ID;


        //States

        $state_waiting_id     = (new Constant())::WAITING_ID;
        $state_published_id   = (new Constant())::PUBLISHED_ID;
        $state_updated_id     = (new Constant())::UPDATED_ID;
        $state_closed_id      = (new Constant())::CLOSED_ID;

        $blogs = Blog::where([
            'state_id'    => $this->constant::PUBLISHED_ID
        ])->get();

        return view('dashboard.entrepreneur.blogs.published',compact(
            'profile_admin_id', 'profile_entrepreneur_id', 'profile_recruiter_id',
            'countries','professions','number_last_messages','last_messages','sectors',
            'publication_date','state_published_id','state_updated_id','state_closed_id',
            'blogs'));
    }

    public function blogs_updated(){
        $last_messages = ContactUs::where(['response' => null])->get();

        $number_last_messages = $last_messages->count();

        $publication_date = $this->date_today->date_today();
        $countries       = Country::all();
        $professions     = Profession::all();
        $sectors         = Sector::all();

        //Profiles
        $profile_admin_id         = (new Constant())::ADMIN_ID;
        $profile_entrepreneur_id  = (new Constant())::ENTREPRENEUR_ID;

        $profile_recruiter_id     = (new Constant())::RECRUITER_ID;


        //States

        $state_waiting_id     = (new Constant())::WAITING_ID;
        $state_published_id   = (new Constant())::PUBLISHED_ID;
        $state_updated_id     = (new Constant())::UPDATED_ID;
        $state_closed_id      = (new Constant())::CLOSED_ID;

        $blogs = Blog::where([
            'state_id'    => $this->constant::UPDATED_ID
        ])->get();

        return view('dashboard.entrepreneur.blogs.updated',compact(
            'profile_admin_id', 'profile_entrepreneur_id', 'profile_recruiter_id',
            'countries','professions','number_last_messages','last_messages','sectors',
            'publication_date','state_published_id','state_updated_id','state_closed_id',
            'blogs'));
    }
    public function blogs_closed(){
        $last_messages = ContactUs::where(['response' => null])->get();

        $number_last_messages = $last_messages->count();

        $publication_date = $this->date_today->date_today();
        $countries       = Country::all();
        $professions     = Profession::all();

        //Profiles
        $profile_admin_id         = (new Constant())::ADMIN_ID;
        $profile_entrepreneur_id  = (new Constant())::ENTREPRENEUR_ID;

        $profile_recruiter_id     = (new Constant())::RECRUITER_ID;


        //States

        $state_waiting_id     = (new Constant())::WAITING_ID;
        $state_published_id   = (new Constant())::PUBLISHED_ID;
        $state_updated_id     = (new Constant())::UPDATED_ID;
        $state_closed_id      = (new Constant())::CLOSED_ID;

        $blogs = Blog::where([
            'state_id'    => $this->constant::CLOSED_ID
        ])->get();
        return view('dashboard.entrepreneur.blogs.closed',compact(
            'profile_admin_id', 'profile_entrepreneur_id', 'profile_recruiter_id',
            'countries','professions','last_messages','number_last_messages',
            'publication_date','state_published_id','state_updated_id',
            'blogs'));
    }

    public function blogs_comments(){
        $last_messages = ContactUs::where(['response' => null])->get();

        $number_last_messages = $last_messages->count();

        $publication_date = $this->date_today->date_today();
        $countries       = Country::all();
        $professions     = Profession::all();

        //Profiles
        $profile_admin_id         = (new Constant())::ADMIN_ID;
        $profile_entrepreneur_id  = (new Constant())::ENTREPRENEUR_ID;

        $profile_recruiter_id     = (new Constant())::RECRUITER_ID;


        //States

        $state_waiting_id     = (new Constant())::WAITING_ID;
        $state_published_id   = (new Constant())::PUBLISHED_ID;
        $state_updated_id     = (new Constant())::UPDATED_ID;
        $state_closed_id      = (new Constant())::CLOSED_ID;

        $blogs = Blog::where([
            'state_id'    => $this->constant::PUBLISHED_ID
        ])->get();
        return view('dashboard.entrepreneur.blogs.comments.index',compact(
            'profile_admin_id', 'profile_entrepreneur_id', 'profile_recruiter_id',
            'countries','professions','last_messages','number_last_messages',
            'publication_date','state_published_id','state_updated_id',
            'blogs'));
    }
}

resources/views/dashboard/blogger/blogs/closed.blade.php
@extends('layouts.master')
@section('content')

    <div class="box-body">

        <!-- Begin Page Content -->
        <div class="container-fluid">

            @if($blogs->isEmpty())
                <h1 style="text-align: center;color: red;">Aucun blog n'a été cloturé</h1>
            @else
            <!-- DataTales Example -->
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Liste de vos blogs cloturés</h6>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead class="thead-dark">
                                <tr>
                                    <th>Titre</th>
                                    <th>Domaine</th>
                                    <th>Image</th>
                                    <th>Date de publication </th>
                                    <th>Description </th>
                                    <th>Etat du blog </th>

                                </tr>
                                </thead>

                                <tbody>
                                @foreach($blogs as $blog)
                                    <tr>
                                        <td class="border px-4 py-2">{{$blog->title}}</td>
                                        <td class="border px-4 py-2">{{$blog->sector-name}}</td>
                                        <img width="90px;" height="8%;" src="{{URL::to('storage/'. $blog->photo)}}">
                                        <td class="border px-4 py-2">{{$blog->publication_date}}</td>
                                        <td class="border px-4 py-2">{{$blog->description}}</td>
                                        <td class="border px-4 py-2" style="color: red">{{$blog->state->description}}</td>

                                        <td>

                                            <button class="btn btn-danger"
                                                    data-userid = "{{$blog->id}}"
                                                    data-toggle="modal"
                                                    data-target="#deleteblog"
                                            >Supprimer</button>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            @endif
        </div>


    </div>

    <div class="modal modal-danger fade" id="deleteblog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title text-center" id="myModalLabel">Confirmation de la suppression</h4>
                </div>
                <form action="{{route('blog.destroy','test')}}" method="post">
                    {{method_field('delete')}}
                    {{csrf_field()}}
                    <div class="modal-body">
                        <p class="text-center">
                            Ëtes-vous sûrs de supprimer ce blog ?
                        </p>
                        <input type="hidden" name="blog_id" id="blog_id">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-success" data-dismiss="modal">Non,Annuler</button>
                        <button type="submit" class="btn btn-warning">Oui,Supprimer</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection

resources/views/dashboard/blogger/blogs/published.blade.php
@extends('layouts.master')
@section('content')

    <div class="box-body">

        <!-- Begin Page Content -->
        <div class="container-fluid">


            @if($blogs->isEmpty())
                <h1 style="text-align: center;color: red;">Aucun blog n'a été publié</h1>
            @else
            <!-- DataTales Example -->
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Liste de vos blogs publiés</h6>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead class="thead-dark">
                                <tr>
                                    <th>Titre</th>
                                    <th>Domaine</th>
                                    <th>Date de publication </th>
                                    <th>Etat du blog </th>

                                </tr>
                                </thead>

                                <tbody>
                                @foreach($blogs as $blog)
                                    <tr>
                                        <td class="border px-4 py-2">{{$blog->title}}</td>
                                        <td class="border px-4 py-2">{{$blog->sector->name}}</td>
                                        <td class="border px-4 py-2">{{$blog->publication_date}}</td>
                                        @if($blog->photo)
                                            <td>
                                                <button style="color: green;"
                                                >
                                                    <a href="{{url('download/blog',$blog->id)}}">
                                                        <i class="fas fa-eye fa-sm">Voir</i>
                                                    </a>
                                                </button>
                                            </td>
                                        @endif
                                        <td class="border px-4 py-2">
                                            <button style="color: green;"
                                                    data-blogid          = "{{$blog->id}}"
                                                    data-toggle="modal"
                                                    data-target="#closeblog"
                                            >{{$blog->state->description}}</button>
                                        </td>
                                        <td>
                                            <button class="btn btn-info"
                                                    data-blogid            = "{{$blog->id}}"
                                                    data-bloggerid         = "{{Auth::user()->id}}"
                                                    data-title             = "{{$blog->title}}"
                                                    data-description       = "{{$blog->description}}"
                                                    data-toggle="modal"
                                                    data-target="#editblog"
                                            >Détails</button>
                                            /
                                            <button class="btn btn-danger"
                                                    data-userid = "{{$blog->id}}"
                                                    data-toggle="modal"
                                                    data-target="#deleteblog"
                                            >Supprimer</button>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!--Modal Edit User-->
                <div class="modal fade" id="editblog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <h4 class="modal-title" id="myModalLabel">Editer un blog</h4>
                            </div>
                            <form action="{{route('blog.update','test')}}" method="post">
                                {{method_field('patch')}}
                                {{csrf_field()}}
                                <div class="modal-body">
                                    <input type="hidden"   name="blog_id" id="blog_id">
                                    <input type="hidden"   name="blogger_id"  id="blogger_id">
                                    <input type="hidden"   name="state_id"  id="state_id">
                                    <input type="hidden"   name="state_id"  value="{{$state_updated_id}}">

                                    <div class="form-group">
                                        <label for="">Titre du blog</label>
                                        <input type="text"  class="form-control" name="title"  id="title">
                                    </div>

                                    <div class="form-group">
                                        <label for="">Description du blog</label>
                                        <textarea type="text" rows="12" class="form-control" name="description"  id="description"></textarea>
                                    </div>

                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
                                    <button type="submit" class="btn btn-primary">Enregistrer les changements</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            @endif
        </div>


    </div>

    <!-- Modal -->

    <div class="modal modal-danger fade" id="closeblog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title text-center" id="myModalLabel">Confirmation de la clôture</h4>
                </div>
                <form action="{{route('blog.show','test')}}" method="get">
                    {{csrf_field()}}
                    <div class="modal-body">
                        <p class="text-center">
                            Voulez-vous clôturer ce blog ?
                        </p>
                        <input type="hidden" name="blog_id" id="blog_id">
                        <input type="hidden" name="state_id" value="{{$state_closed_id}}">

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-success" data-dismiss="modal">Non,Annuler</button>
                        <button type="submit" class="btn btn-warning">Oui,Clôturer</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="modal modal-danger fade" id="deleteblog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title text-center" id="myModalLabel">Confirmation de la suppression</h4>
                </div>
                <form action="{{route('blog.destroy','test')}}" method="post">
                    {{method_field('delete')}}
                    {{csrf_field()}}
                    <div class="modal-body">
                        <p class="text-center">
                            Ëtes-vous sûrs de supprimer ce blog ?
                        </p>
                        <input type="hidden" name="blog_id" id="blog_id">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-success" data-dismiss="modal">Non,Annuler</button>
                        <button type="submit" class="btn btn-warning">Oui,Supprimer</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection